apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhoai-chat-bot-test 
  janus-idp.io/tekton: rhoai-chat-bot-test
  backstage.io/kubernetes-id: rhoai-chat-bot-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhoai-chat-bot-test
resources: 
- application-dev.yaml